### ISSUE TITLE
How to make it animate from right to left?

### ISSUE THREAD

**Issue by lucasjinreal** [Imgkl/anim_search_bar#1]
I have a demands that wanna make the expanded animation from right to left. Is possible to do this?

**Comment by Imgkl** [comment]
Hello @jinfagang 
This is one of the feature, that I'm currently working on. Will update the package soon.

**Comment by Imgkl** [comment]
I have updated the package. Please update the package to version `0.0.7`. and use the rtl support.

````
AnimSearchBar(
        rtl: true, // use true to make the search bar to expand from right to left
        width: 400,
        textController: textController,
        onSuffixTap: () {
          setState(() {
            textController.clear();
          });
        },
      ),

````

**Comment by Imgkl** [comment]
Hey @jinfagang ,

I'm closing this issue as this feature is added on the version `0.0.7`. 

Reopen this issue, if you feel the implementation has any problem.
