### ISSUE TITLE
onSuffixTap not working

### ISSUE THREAD

**Issue by michelebanfi** [Imgkl/anim_search_bar#10]
onSuffixTap parameter dosen't work, and is never called.

**Comment by Imgkl** [comment]
@michelebanfi thanks for bringing this issue to my notice. I’ll push a hotfix right away.

**Comment by Imgkl** [comment]
Hello @michelebanfi ,

I've tested the plugin just now, `onSuffixTap` is working fine. Can you share your code along with your flutter doctor log.

**Comment by michelebanfi** [comment]
**code**
class Search extends StatefulWidget {
  @override
  _SearchState createState() => _SearchState();
}

class _SearchState extends State<Search> {
  TextEditingController textController = TextEditingController();
  @override
  Widget build(BuildContext context) {
    return Container(
        child: AnimSearchBar(
      width: 400,
      textController: textController,
      suffixIcon: Icon(Icons.search),
      onSuffixTap: () {
        setState(() {
          textController.clear();
        });
      },
    ));
  }
}
 **flutter doctor**

this bug occur on both and ios and android

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2 20D64 darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by michelebanfi** [comment]
I just change the margin of the search bar and everything is working fine now. Thanks anyway

**Comment by Imgkl** [comment]
@michelebanfi Great. If you face any issues, please feel to open an issue.
