### ISSUE TITLE
[bug] the widget will brings the keyboard up after call ScaffoldState.openDrawer 

### ISSUE THREAD

**Issue by darkh** [Imgkl/anim_search_bar#11]
I think rather than using

`FocusScope.of(context).unfocus();`

you should use 

`FocusManager.instance.primaryFocus.unfocus();`

for more information about this issues please check the follow issues https://github.com/flutter/flutter/issues/54277
because same thing happens right now for the widget

**Comment by Imgkl** [comment]
Hi @darkh,

Thanks for pointing this out. I will fix the issue and update the package soon.

I really appreciate your contribution. 👍🏽✌🏽
