### ISSUE TITLE
Detect if search bar is open or closed

### ISSUE THREAD

**Issue by arvie9** [Imgkl/anim_search_bar#27]
I would like to track if the search bar is open or closed. Is this possible?

**Comment by nicks258** [comment]
Implemented the same Kindly use `https://github.com/nicks258/anim_search_bar`. Implemented callback `searchBarOpen ` which will return 0 or 1 accordingly.

**Comment by arvie9** [comment]
Wow, awesome! I'll check it out, thanks! 🙏🏽
