### ISSUE TITLE
Add Custom color for the  search component

### ISSUE THREAD

**Issue by kherldhussein** [Imgkl/anim_search_bar#4]
Could not add custom color its just the default white (0xffffff)

**Comment by kherldhussein** [comment]
[img](https://camo.githubusercontent.com/a0ac1ac53b50d5da461ee351be07c81a528ce88c4910eba9cc398681d8fc81c7/68747470733a2f2f692e6962622e636f2f597950676b67672f657a6769662d636f6d2d6769662d6d616b65722e676966)

**Comment by Imgkl** [comment]
@kherld-hussein I'll add the capability to change the search bar's color, soon.
