### ISSUE TITLE
Style and text space problem

### ISSUE THREAD

**Issue by XOneto9** [Imgkl/anim_search_bar#8]
Hi, I'm David.

I think this module is very nice with animation and simple UI
Well, anyway, I have some questions. 

 I think this module has to need more options style.
 -  when adopting the theme, the left arrow which is based on setting Icon is not changed color.
 -  text spacing. the text space  I think is short for me.
 
Next) 
I don't know how to do this problem.
when I write text over space then all written text is not show anything.
but if remove some characters to fit text space, then characters are shown.

how can I fix it?

**Comment by Imgkl** [comment]
@XOneto9 Hello David,

Thanks for your kind words about this package. Really appreciate it.

 - Support for dynamic theme will be out really soon. That's something I've been working on lately.
 - I haven't tweaked the letter spacing, but if you feel the letter spacing is short for you, you can pass the `TextStyle` using `style` parameter and adjust the `letterSpacing`.

**Comment by Imgkl** [comment]
> when I write text over space then all written text is not show anything.
but if remove some characters to fit text space, then characters are shown.

Can you please post any screen recording of what the issue that you facing. That'll be helpful for me address it quickly.

**Comment by XOneto9** [comment]
@Imgkl 

Oh,, I will post recoding or some screenshot as soon as possible. Now night! See you soon! 😃

**Comment by Imgkl** [comment]
@XOneto9  

I've identified the text disappearing issue and I've fixed it. Will update the package soon.

**Comment by XOneto9** [comment]
@Imgkl 
oh,, today, I was trying again to test. it was fixed! great!
very nice.

and could you make me change the style of the search-bar?
I want to move the search-bar shadow because of the ambiguous borderline.

maybe you understand the below image.

![IMG_4546](https://user-images.githubusercontent.com/18350072/111909189-a1910100-8a9f-11eb-8a26-7d7ed43415f1.jpeg)


so, I think that I need to options of adjusting the value of the search-bar style.

**Comment by XOneto9** [comment]
@Imgkl 

your work is great to fix the bug!  also, it's work to me.
the characters overwritten is shown!

but something remain problem.

1. the search bar borderline is ambiguous because of being under-shadow effect.
2. when I adopted dark mode theme, the left arrow is not shown

So how about making options to customizeing design or adjust of search-bar style?

![IMG_4546 오후 11 58 14](https://user-images.githubusercontent.com/18350072/111909938-968ba000-8aa2-11eb-9487-401372b7a770.jpeg)
![IMG_4548](https://user-images.githubusercontent.com/18350072/111909941-97243680-8aa2-11eb-833e-9162ca893440.jpeg)

**Comment by saigkl** [comment]
@XOneto9 Yes, this is WIP, this is a known bug related to dynamic theming. Will resolve it soon. Appreciate your patience.
